apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-eransery-app
  labels:
    app: pod-eransery-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: pod-eransery-app  
  template:
    metadata:
      labels:
        app: pod-eransery-app
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}        